dependencies:
  - name: elasticsearch
    version: 7.5.2
    repository: https://helm.elastic.co
    alias: elasticsearch
  - name: elasticsearch-curator
    version: 2.1.3
    repository: https://kubernetes-charts.storage.googleapis.com
    alias: curator
  - name: kibana
    version: 7.5.2
    repository: https://helm.elastic.co
    alias: kibana
  - name: fluent-bit
    version: 2.8.7
    repository: https://kubernetes-charts.storage.googleapis.com
    alias: fluentbit
  - name: metricbeat
    version: 7.5.2
    repository: https://helm.elastic.co
    alias: metricbeat